server:
  port: 8888
spring:
  mail:
    host: smtp.163.com #发送邮件服务器 QQ: smtp.qq.com 网易: smtp.163.com
    username: 你的邮箱 #发送邮件的邮箱地址 QQ: 176****919@qq.com 网易: 184****0305@163.com
    password: 邮箱授权码 #客户端授权码  QQ: 查看邮箱设置 网易: 查看邮箱设置
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8